### ISSUE TITLE
How to run this application ? 

### ISSUE THREAD

**Issue by aalzooke** [jinnovation/derain-net#4]
Can you please explain how to run this application for a single image.
Thank you

**Comment by Hrhythm** [comment]
I run the code by this :  
python derain.py C:\Users\70579\Desktop\timg.jpg
but throw the error ：
(base) C:\Users\70579\practice\derain-net-master>python derain.py C:\Users\70579\Desktop\timg.jpg
Traceback (most recent call last):
  File "derain.py", line 24, in <module>
    img_base, img_detail = img.split(imread(args.input))
  File "C:\Users\70579\practice\derain-net-master\img.py", line 4, in split
    gf = FastGuidedFilter(img, 16, 2, 4)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\guided_filter\core\filters.py", line 58, in __init__
    I_sub = _downSample(I_32F, scale)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\guided_filter\core\filters.py", line 31, in _downSample
    return cv2.resize(I, (w / scale, h / scale), interpolation=cv2.INTER_NEAREST)
TypeError: integer argument expected, got float

So how to run your code ? thank U !

**Comment by zhaojianghe16** [comment]
@Hrhythm  try the train.py

**Comment by jinnovation** [comment]
This project is very much a work in progress at the moment. Sorry for the inconvenience you're experiencing, but thanks a lot for the attention. Please feel free to keep an eye on this repo for updates as they come up.
